openapi: 3.0.0
info:
  title: S2S XML-RPC RNG API
  version: '1.0'
  description: Szrek2Solutions Random Number Generator API using XML-RPC
  contact:
    url: 'http://www.szrek.com'
    email: info@szrek.com
servers:
  - url: 'http://localhost:53380'
    description: Local RNG
paths:
  /RPC2:
    post:
      summary: test
      tags: []
      responses: {}
      operationId: post-RPC2
    parameters: []
components:
  schemas: {}
definitions:
  GetRandomResponse:
    type: object
    properties:
      name:
        type: string
        x-field-number: 2
